# Generated by Django 2.2.4 on 2019-09-04 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=250)),
                ('Publish_Date', models.DateTimeField()),
                ('Image', models.ImageField(upload_to='Images/')),
                ('Body', models.TextField()),
            ],
        ),
    ]
